[package]
name = "test_infra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

vm = { git = "https://github.com/ZKAmoeba-Micro/micro.git", branch = "boojum-integration" }
micro_types = { git = "https://github.com/ZKAmoeba-Micro/micro.git", branch = "boojum-integration" }
micro_contracts = { git = "https://github.com/ZKAmoeba-Micro/micro.git", branch = "boojum-integration" }
micro_utils = { git = "https://github.com/ZKAmoeba-Micro/micro.git", branch = "boojum-integration" }
micro_state = { git = "https://github.com/ZKAmoeba-Micro/micro.git", branch = "boojum-integration" }
vlog = { git = "https://github.com/ZKAmoeba-Micro/micro.git", branch = "boojum-integration" }

colored = "2.0"
hex = "0.4"
once_cell = "1.7"
tracing = { version = "0.1.26", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "time", "json"] }
serde_json = "1.0.67"
serde = { version = "1.0", features = ["derive"] }
